<?php

namespace app\components;

use yii\base\Exception;
use yii\db\Command;

class FakeDatabaseCommand extends Command
{
    public array $bigTables = [];

    public function init(): void
    {
        parent::init();
        $this->bigTables = array_map(
            function ($table) {
                return $this->db->quoteTableName($table);
            },
            $this->bigTables
        );
    }

    public function dropTable($table)
    {
        $this->checkTableName($table);
        return parent::dropTable($table);
    }

    private function checkTableName(string $table): void
    {
        $table = $this->db->quoteTableName($table);
        $table = strtolower($table);
        if (in_array($table, $this->bigTables, true)) {
            throw new Exception("Опасная миграция на таблице $table");
        }
    }

    public function createIndex($name, $table, $columns, $unique = false)
    {
        $this->checkTableName($table);
        return parent::createIndex($name, $table, $columns, $unique);
    }

    public function addCheck($name, $table, $expression)
    {
        $this->checkTableName($table);
        return parent::addCheck($name, $table, $expression);
    }

    public function addUnique($name, $table, $columns)
    {
        $this->checkTableName($table);
        return parent::addUnique($name, $table, $columns);
    }

    public function addColumn($table, $column, $type)
    {
        $this->checkTableName($table);
        return parent::addColumn($table, $column, $type);
    }

    public function dropColumn($table, $column)
    {
        $this->checkTableName($table);
        return parent::dropColumn($table, $column);
    }

    public function addForeignKey($name, $table, $columns, $refTable, $refColumns, $delete = null, $update = null)
    {
        $this->checkTableName($table);
        return parent::addForeignKey(
            $name,
            $table,
            $columns,
            $refTable,
            $refColumns,
            $delete,
            $update
        ); // TODO: Change the autogenerated stub
    }

    public function alterColumn($table, $column, $type)
    {
        $this->checkTableName($table);
        return parent::alterColumn($table, $column, $type);
    }
}
