name: Check migrations

on: push
env:
  MYSQL_ROOT_PASSWORD: qweasdzxc

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: files
        uses: vyachin/get-changed-files@v3
        with:
          branch: master

      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '5.6'
          mysql database: test
          mysql root password: $MYSQL_ROOT_PASSWORD

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: xdebug
          tools: composer

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=$MYSQL_ROOT_PASSWORD --silent; do
            sleep 1
          done

      - name: Install dependencies with composer
        run: composer install --prefer-dist --no-suggest --no-progress

      - name: Generate config
        run: |
          echo "<?php

                use app\components\FakeDatabaseCommand;
                use app\components\MigrateCommand;
                use yii\console\controllers\MigrateController;
                use yii\db\Connection;

                return [
                    'id' => 'check-migrations',
                    'basePath' => dirname(__DIR__),
                    'container' => [
                        'definitions' => [
                            FakeDatabaseCommand::class => [
                                'bigTables' => preg_split('#\s+#', $_SERVER['BIG_TABLES'] ?? ''),
                            ],
                            MigrateController::class => [
                                'class' => MigrateCommand::class,
                                'changeFiles' => preg_split('#\s+#', $_SERVER['CHANGED_FILES'] ?? ''),
                            ],
                        ],
                    ],
                    'components' => [
                        'db' => [
                            'class' => Connection::class,
                            'dsn' => 'mysql:host=127.0.0.1;dbname=test',
                            'username' => 'root',
                            'password' => 'qweasdzxc',
                            'enableLogging' => true,
                            'enableProfiling' => true,
                        ],
                    ],
                ];
          " > config/main.php

      - name: Check migrations
        run: php yii migrate/up --interactive=0
        env:
          CHANGED_FILES: ${{ steps.files.outputs.all }}
          BIG_TABLES: table1
